package com.orlando.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-09-29T13:19:34.071-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "CreatePersonServiceImplService",
                  wsdlLocation = "http://localhost:8080/cxfSoap/CreatePersonService?wsdl",
                  targetNamespace = "http://ws.orlando.com/")
public class CreatePersonServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.orlando.com/", "CreatePersonServiceImplService");
    public final static QName CreatePersonServiceImplPort = new QName("http://ws.orlando.com/", "CreatePersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfSoap/CreatePersonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreatePersonServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfSoap/CreatePersonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreatePersonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreatePersonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreatePersonServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreatePersonServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreatePersonServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreatePersonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreatePersonService
     */
    @WebEndpoint(name = "CreatePersonServiceImplPort")
    public CreatePersonService getCreatePersonServiceImplPort() {
        return super.getPort(CreatePersonServiceImplPort, CreatePersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreatePersonService
     */
    @WebEndpoint(name = "CreatePersonServiceImplPort")
    public CreatePersonService getCreatePersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CreatePersonServiceImplPort, CreatePersonService.class, features);
    }

}
