package com.orlando.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-09-29T13:19:34.067-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.orlando.com/", name = "CreatePersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface CreatePersonService {

    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.CreatePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        com.orlando.ws.Person arg0
    );
}
