package com.orlando.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-13T13:46:16.439-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "DeletePersonServiceImplService",
                  wsdlLocation = "http://localhost:8080/cxfSoap/DeletePersonService?wsdl",
                  targetNamespace = "http://ws.orlando.com/")
public class DeletePersonServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.orlando.com/", "DeletePersonServiceImplService");
    public final static QName DeletePersonServiceImplPort = new QName("http://ws.orlando.com/", "DeletePersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfSoap/DeletePersonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeletePersonServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfSoap/DeletePersonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeletePersonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeletePersonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeletePersonServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeletePersonServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeletePersonServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeletePersonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeletePersonService
     */
    @WebEndpoint(name = "DeletePersonServiceImplPort")
    public DeletePersonService getDeletePersonServiceImplPort() {
        return super.getPort(DeletePersonServiceImplPort, DeletePersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeletePersonService
     */
    @WebEndpoint(name = "DeletePersonServiceImplPort")
    public DeletePersonService getDeletePersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DeletePersonServiceImplPort, DeletePersonService.class, features);
    }

}
