package com.orlando.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-13T13:46:16.435-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.orlando.com/", name = "DeletePersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeletePersonService {

    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.DeletePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
