package com.orlando.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-06T10:34:52.226-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.orlando.com/", name = "RetrieveStatesService")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrieveStatesService {

    @WebMethod
    @RequestWrapper(localName = "getAllStates", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.GetAllStates")
    @ResponseWrapper(localName = "getAllStatesResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.GetAllStatesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.orlando.ws.State> getAllStates();
}
