package com.orlando.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-06T10:33:05.780-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "RetrieveCitiesServiceImplService",
                  wsdlLocation = "http://localhost:8080/cxfSoap/RetrieveCitiesService?wsdl",
                  targetNamespace = "http://ws.orlando.com/")
public class RetrieveCitiesServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.orlando.com/", "RetrieveCitiesServiceImplService");
    public final static QName RetrieveCitiesServiceImplPort = new QName("http://ws.orlando.com/", "RetrieveCitiesServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfSoap/RetrieveCitiesService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RetrieveCitiesServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfSoap/RetrieveCitiesService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RetrieveCitiesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RetrieveCitiesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetrieveCitiesServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RetrieveCitiesServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RetrieveCitiesServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RetrieveCitiesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RetrieveCitiesService
     */
    @WebEndpoint(name = "RetrieveCitiesServiceImplPort")
    public RetrieveCitiesService getRetrieveCitiesServiceImplPort() {
        return super.getPort(RetrieveCitiesServiceImplPort, RetrieveCitiesService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetrieveCitiesService
     */
    @WebEndpoint(name = "RetrieveCitiesServiceImplPort")
    public RetrieveCitiesService getRetrieveCitiesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RetrieveCitiesServiceImplPort, RetrieveCitiesService.class, features);
    }

}
