package com.orlando.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-06T13:00:20.976-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "RetrievePersonServiceImplService",
                  wsdlLocation = "http://localhost:8080/cxfSoap/RetrievePersonService?wsdl",
                  targetNamespace = "http://ws.orlando.com/")
public class RetrievePersonServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.orlando.com/", "RetrievePersonServiceImplService");
    public final static QName RetrievePersonServiceImplPort = new QName("http://ws.orlando.com/", "RetrievePersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfSoap/RetrievePersonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RetrievePersonServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfSoap/RetrievePersonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RetrievePersonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RetrievePersonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetrievePersonServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RetrievePersonServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RetrievePersonServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RetrievePersonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RetrievePersonService
     */
    @WebEndpoint(name = "RetrievePersonServiceImplPort")
    public RetrievePersonService getRetrievePersonServiceImplPort() {
        return super.getPort(RetrievePersonServiceImplPort, RetrievePersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetrievePersonService
     */
    @WebEndpoint(name = "RetrievePersonServiceImplPort")
    public RetrievePersonService getRetrievePersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RetrievePersonServiceImplPort, RetrievePersonService.class, features);
    }

}
