package com.orlando.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-06T13:00:20.973-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.orlando.com/", name = "RetrievePersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrievePersonService {

    @WebMethod
    @RequestWrapper(localName = "findById", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.orlando.ws.Person findById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.orlando.ws.Person> findAll();

    @WebMethod
    @RequestWrapper(localName = "findByEmail", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindByEmail")
    @ResponseWrapper(localName = "findByEmailResponse", targetNamespace = "http://ws.orlando.com/", className = "com.orlando.ws.FindByEmailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.orlando.ws.Person findByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
