package com.orlando.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-13T13:50:42.760-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "UpdatePersonServiceImplService",
                  wsdlLocation = "http://localhost:8080/cxfSoap/UpdatePersonService?wsdl",
                  targetNamespace = "http://ws.orlando.com/")
public class UpdatePersonServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.orlando.com/", "UpdatePersonServiceImplService");
    public final static QName UpdatePersonServiceImplPort = new QName("http://ws.orlando.com/", "UpdatePersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfSoap/UpdatePersonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UpdatePersonServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfSoap/UpdatePersonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UpdatePersonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UpdatePersonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdatePersonServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UpdatePersonServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UpdatePersonServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UpdatePersonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UpdatePersonService
     */
    @WebEndpoint(name = "UpdatePersonServiceImplPort")
    public UpdatePersonService getUpdatePersonServiceImplPort() {
        return super.getPort(UpdatePersonServiceImplPort, UpdatePersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdatePersonService
     */
    @WebEndpoint(name = "UpdatePersonServiceImplPort")
    public UpdatePersonService getUpdatePersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UpdatePersonServiceImplPort, UpdatePersonService.class, features);
    }

}
