package com.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T10:18:34.043-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.jaxws.com/", name = "CreateUserService")
@XmlSeeAlso({ObjectFactory.class})
public interface CreateUserService {

    @WebMethod
    @RequestWrapper(localName = "insertUser", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.InsertUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String insertUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.jaxws.ws.User arg0
    );
}
