package com.jaxws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T10:18:34.046-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "CreateUserServiceImplService",
                  wsdlLocation = "http://localhost:8080/Jaxws-demo/CreateUserService?wsdl",
                  targetNamespace = "http://ws.jaxws.com/")
public class CreateUserServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.jaxws.com/", "CreateUserServiceImplService");
    public final static QName CreateUserServiceImplPort = new QName("http://ws.jaxws.com/", "CreateUserServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Jaxws-demo/CreateUserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateUserServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Jaxws-demo/CreateUserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateUserServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateUserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateUserServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateUserServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateUserServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateUserServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreateUserService
     */
    @WebEndpoint(name = "CreateUserServiceImplPort")
    public CreateUserService getCreateUserServiceImplPort() {
        return super.getPort(CreateUserServiceImplPort, CreateUserService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateUserService
     */
    @WebEndpoint(name = "CreateUserServiceImplPort")
    public CreateUserService getCreateUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CreateUserServiceImplPort, CreateUserService.class, features);
    }

}
