package com.jaxws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T14:11:45.409-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "DeleteUserServiceImplService",
                  wsdlLocation = "http://localhost:8080/Jaxws-demo/DeleteUserService?wsdl",
                  targetNamespace = "http://ws.jaxws.com/")
public class DeleteUserServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.jaxws.com/", "DeleteUserServiceImplService");
    public final static QName DeleteUserServiceImplPort = new QName("http://ws.jaxws.com/", "DeleteUserServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Jaxws-demo/DeleteUserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeleteUserServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Jaxws-demo/DeleteUserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeleteUserServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeleteUserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteUserServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeleteUserServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeleteUserServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeleteUserServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeleteUserService
     */
    @WebEndpoint(name = "DeleteUserServiceImplPort")
    public DeleteUserService getDeleteUserServiceImplPort() {
        return super.getPort(DeleteUserServiceImplPort, DeleteUserService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteUserService
     */
    @WebEndpoint(name = "DeleteUserServiceImplPort")
    public DeleteUserService getDeleteUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DeleteUserServiceImplPort, DeleteUserService.class, features);
    }

}
