package com.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T14:11:45.404-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.jaxws.com/", name = "DeleteUserService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeleteUserService {

    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.DeleteUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
