package com.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-12T09:42:32.521-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.jaxws.com/", name = "RetrieveStatesService")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrieveStatesService {

    @WebMethod
    @RequestWrapper(localName = "getAll", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.jaxws.ws.State> getAll();
}
