package com.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-12T13:05:13.795-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.jaxws.com/", name = "RetrieveUserService")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrieveUserService {

    @WebMethod
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.jaxws.ws.User> getAllUsers();

    @WebMethod
    @RequestWrapper(localName = "getUserByEmail", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetUserByEmail")
    @ResponseWrapper(localName = "getUserByEmailResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetUserByEmailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.jaxws.ws.User getUserByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.jaxws.ws.User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
