package com.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-12T09:40:27.298-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.jaxws.com/", name = "RetrieveCitiesService")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrieveCitiesService {

    @WebMethod
    @RequestWrapper(localName = "getAllByState", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAllByState")
    @ResponseWrapper(localName = "getAllByStateResponse", targetNamespace = "http://ws.jaxws.com/", className = "com.jaxws.ws.GetAllByStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.jaxws.ws.City> getAllByState(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
